### ISSUE TITLE
Too strict with respect to type parameters

### ISSUE THREAD

**Issue by epatters** [schlichtanders/StructEquality.jl#5]
Nice package! I'd like to use it but the way type parameters are currently handled is too strict for me.

Usually in Julia, type parameters in containers don't affect equality comparisons of their contents, e.g.

```julia
julia> Any[1,2,3] == [1,2,3]
true
```

But they do here:

```julia
julia> @struct_equal struct Foo{T}
       x::T
       end

julia> Foo(1) == Foo(1)
true

julia> Foo{Any}(1) == Foo(1)
false
```

Would it be possible to change this behavior?

**Comment by schlichtanders** [comment]
Thank you @epatters for your help.

The goal of the package is to have intuitive struct comparison. As typevars are anyway instable in julia (as they can change depending on luck on the compiler type inference), I now included the change to master.

Can you check whether StructEquality#master works for your cases?
Then I am going to make a new patch release

**Comment by epatters** [comment]
Thanks so much for making this improvement! I can confirm that the package is now working as expected for me.

**Comment by schlichtanders** [comment]
Version 2.1.0 is just released, including the fix.
